apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-page
  template:
    metadata:
      labels: 
        app: web-page
        environment: dev
    spec:
       containers:
        - name:  webpage
          image: mehrjay86/assign4
          ports:
            - containerPort: 8080
